// Code generated by mockery v2.53.5. DO NOT EDIT.

package routermocks

import (
	context "context"
	pr "pullreq/internal/pr"

	mock "github.com/stretchr/testify/mock"
)

// PullRequestRepoInterface is an autogenerated mock type for the PullRequestRepoInterface type
type PullRequestRepoInterface struct {
	mock.Mock
}

// AssignedReviewer provides a mock function with given fields: ctx, PrID, UserID
func (_m *PullRequestRepoInterface) AssignedReviewer(ctx context.Context, PrID string, UserID string) (*pr.PullRequest, string, error) {
	ret := _m.Called(ctx, PrID, UserID)

	if len(ret) == 0 {
		panic("no return value specified for AssignedReviewer")
	}

	var r0 *pr.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*pr.PullRequest, string, error)); ok {
		return rf(ctx, PrID, UserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *pr.PullRequest); ok {
		r0 = rf(ctx, PrID, UserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pr.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, PrID, UserID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, PrID, UserID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Check provides a mock function with given fields: ctx, ID
func (_m *PullRequestRepoInterface) Check(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, req
func (_m *PullRequestRepoInterface) Create(ctx context.Context, req pr.CreatePullRequestRequest) (*pr.PullRequest, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *pr.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pr.CreatePullRequestRequest) (*pr.PullRequest, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pr.CreatePullRequestRequest) *pr.PullRequest); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pr.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pr.CreatePullRequestRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPr provides a mock function with given fields: ctx, ID
func (_m *PullRequestRepoInterface) GetPr(ctx context.Context, ID string) (*pr.PullRequest, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetPr")
	}

	var r0 *pr.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pr.PullRequest, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pr.PullRequest); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pr.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Merged provides a mock function with given fields: ctx, ID
func (_m *PullRequestRepoInterface) Merged(ctx context.Context, ID string) (*pr.PullRequest, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Merged")
	}

	var r0 *pr.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pr.PullRequest, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pr.PullRequest); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pr.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPullRequestRepoInterface creates a new instance of PullRequestRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepoInterface {
	mock := &PullRequestRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
