// Code generated by mockery v2.53.5. DO NOT EDIT.

package routermocks

import (
	context "context"
	team "pullreq/internal/team"

	mock "github.com/stretchr/testify/mock"

	user "pullreq/internal/user"
)

// TeamRepoInterface is an autogenerated mock type for the TeamRepoInterface type
type TeamRepoInterface struct {
	mock.Mock
}

// AddTeam provides a mock function with given fields: ctx, teamName, members
func (_m *TeamRepoInterface) AddTeam(ctx context.Context, teamName string, members []team.TeamMember) (*team.Team, error) {
	ret := _m.Called(ctx, teamName, members)

	if len(ret) == 0 {
		panic("no return value specified for AddTeam")
	}

	var r0 *team.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []team.TeamMember) (*team.Team, error)); ok {
		return rf(ctx, teamName, members)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []team.TeamMember) *team.Team); ok {
		r0 = rf(ctx, teamName, members)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []team.TeamMember) error); ok {
		r1 = rf(ctx, teamName, members)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Deactivation provides a mock function with given fields: ctx, teanName
func (_m *TeamRepoInterface) Deactivation(ctx context.Context, teanName string) error {
	ret := _m.Called(ctx, teanName)

	if len(ret) == 0 {
		panic("no return value specified for Deactivation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teanName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTeamByUserID provides a mock function with given fields: ctx, userID
func (_m *TeamRepoInterface) GetTeamByUserID(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamMember provides a mock function with given fields: ctx, teamID
func (_m *TeamRepoInterface) GetTeamMember(ctx context.Context, teamID int) ([]*user.User, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMember")
	}

	var r0 []*user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*user.User, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*user.User); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamWithMembers provides a mock function with given fields: ctx, teamName
func (_m *TeamRepoInterface) GetTeamWithMembers(ctx context.Context, teamName string) (*team.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamWithMembers")
	}

	var r0 *team.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*team.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *team.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamRepoInterface creates a new instance of TeamRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepoInterface {
	mock := &TeamRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
