// Code generated by mockery v2.53.5. DO NOT EDIT.

package routermocks

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"

	user "pullreq/internal/user"
)

// UserRepoInterface is an autogenerated mock type for the UserRepoInterface type
type UserRepoInterface struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, tx, _a2
func (_m *UserRepoInterface) AddUser(ctx context.Context, tx *sql.Tx, _a2 *user.User) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, *user.User) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStatAboutUser provides a mock function with given fields: ctx, userID
func (_m *UserRepoInterface) GetStatAboutUser(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatAboutUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersPrShort provides a mock function with given fields: ctx, userID
func (_m *UserRepoInterface) GetUsersPrShort(ctx context.Context, userID string) ([]user.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersPrShort")
	}

	var r0 []user.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]user.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []user.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, _a1
func (_m *UserRepoInterface) UpdateUser(ctx context.Context, _a1 user.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserActivity provides a mock function with given fields: ctx, userID, isActive
func (_m *UserRepoInterface) UpdateUserActivity(ctx context.Context, userID string, isActive bool) (*user.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserActivity")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*user.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *user.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepoInterface creates a new instance of UserRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepoInterface {
	mock := &UserRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
